### ISSUE TITLE
Need GtkFileDialog implementation

### ISSUE THREAD

**Issue by arunkd13** [eugeniodepalo/react-native-gtk4#63]
I need the GtkFileDialog for my app for which I do not see a component built yet. Is this something that is missing currently?

If I wanted to implement it myself, would following the example of [PrintUnixDialog](https://github.com/eugeniodepalo/react-native-gtk4/blob/main/packages/react-native-gtk4/src/components/PrintUnixDialog.tsx) help?

**Comment by arunkd13** [comment]
I get the following error when using it in a test application:

```
~/workspace/learn-react-native-gtk4$ npm start

> learn-react-native-gtk4@1.0.0 start
> npm run build && node dist/index.js


> learn-react-native-gtk4@1.0.0 build
> tsc


(process:11557): Gtk-WARNING **: 12:36:01.033: Locale not supported by C library.
        Using the fallback 'C' locale.
The above error occurred in the <SingleFileDialog> component:

    at SingleFileDialog (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/FileDialog.js:35:29)
    at Box
    at ApplicationWindow
    at ApplicationWindowComponent (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/ApplicationWindow.js:34:81)
    at App (/home/arunkumar/workspace/learn-react-native-gtk4/dist/components/App.js:29:61)
    at ApplicationProvider (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/ApplicationProvider.js:29:32)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
[INFO] loop.cc: QuitLoopStack: 173: calling (anonymous)
/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:2950
      throw error;
      ^

TypeError: node_gtk_4_0_1.default.FileDialog is not a constructor
    at /home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/FileDialog.js:14:16
    at mountMemo (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:7579:19)
    at Object.useMemo (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:8024:16)
    at useMemo (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react/cjs/react.development.js:1650:21)
    at useFileDialog (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/FileDialog.js:13:32)
    at SingleFileDialog (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-native-gtk4/dist/components/FileDialog.js:37:20)
    at renderWithHooks (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:6659:18)
    at mountIndeterminateComponent (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:11276:13)
    at beginWork (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:12799:16)
    at beginWork$1 (/home/arunkumar/workspace/learn-react-native-gtk4/node_modules/react-reconciler/cjs/react-reconciler.development.js:19608:14)

Node.js v18.19.0
```

**Comment by arunkd13** [comment]
Ah, looks like I have 4.8.3 coming with Debian 12 (bookworm).

Thanks for the quick support.
